export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_STUDENT = 'GET_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const CLEAR_STUDENT = 'CLEAR_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';